export const monthlyData = [
  {
    month: 'Jan',
    Published: 21,
    Abstract: 42,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Feb',
    Published: 32,
    Abstract: 45,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Mar',
    Published: 17,
    Abstract: 24,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Apr',
    Published: 56,
    Abstract: 2,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'May',
    Published: 35,
    Abstract: 56,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Jun',
    Published: 83,
    Abstract: 54,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Aug',
    Published: 23,
    Abstract: 32,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Sep',
    Published: 78,
    Abstract: 43,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 76,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Oct',
    Published: 15,
    Abstract: 9,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Nov',
    Published: 29,
    Abstract: 18,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
  {
    month: 'Dec',
    Published: 69,
    Abstract: 96,
    Presentation: 21,
    JournalArticle: 18,
    Datasets: 51,
    Report: 56,
    ConferenceProceedings: 27,
    Other: 87,
    Brochure: 44,
    BookChapter: 123,
    Video: 79,
    Book: 66,
    Exhibit: 39,
    Software: 12,
    Magazine: 3,
  },
];
